### PR TITLE
add new blog post for January release

### PR DESCRIPTION
**Pull request by mayasingh17**
# First iteration of the Blog Post for v0.24.0 January Release

I added the blog post content along with two images, a post-image, and the enums to string image

## How to use

please review the website test to see what the content looks like

## Testing done

I need to review the stage site to see what the website would look like

### CODE REVIEW

**Comment by mayasingh17** [comment]
@blixtra  I've uploaded a V1 and found a couple issues: 1)my name is not formatting correctly, perhaps it needs to be configured in an underlying database? 2) the links in the table of contents aren't navigating to the correct subsections. This is probably an issue with the markdown logic.

**Comment by alban** [comment]
@mayasingh17 Your name can be added in data/references/authors.yml

**Comment by mayasingh17** [comment]
I fixed the links issue, except the last one isn't quite working due to some markdown syntax issues, I also need to update the data/reference/authors.yml file because I totally forgot, I'll do those on the next push, thanks for everyone's patience.

**Comment by mayasingh17** [comment]
@blixtra I think this is good to go now. LMK your thoughts.

**Pull request merged**
